; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{35E6673D-F7AE-4D15-BCA8-D31FD8FE6E5D}
AppName=Gestion De Stock
AppVersion=0.1
;AppVerName=Gestion De Stock 0.1
AppPublisher=l'Institut Technique d'Aadministration et de Gestion
AppPublisherURL=We D'ont Have a Website For the Moment!!
AppSupportURL=We D'ont Have a Website For the Moment!!
AppUpdatesURL=We D'ont Have a Website For the Moment!!
DefaultDirName={pf}\Gestion De Stock
DisableProgramGroupPage=yes
OutputDir=C:\Users\hp\Desktop\pff\pfe Realis
OutputBaseFilename=Gestion_Stock_Innsaller
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\hp\Desktop\Projet_Fin_Formation\Projet_Fin_Formation\bin\Debug\Projet_Fin_Formation.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Desktop\Projet_Fin_Formation\Projet_Fin_Formation\bin\Debug\Projet_Fin_Formation.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Desktop\Projet_Fin_Formation\Projet_Fin_Formation\bin\Debug\Projet_Fin_Formation.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Desktop\Projet_Fin_Formation\Projet_Fin_Formation\bin\Debug\Projet_Fin_Formation.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Desktop\Projet_Fin_Formation\Projet_Fin_Formation\bin\Debug\Projet_Fin_Formation.vshost.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Desktop\Projet_Fin_Formation\Projet_Fin_Formation\bin\Debug\Projet_Fin_Formation.vshost.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Gestion De Stock"; Filename: "{app}\Projet_Fin_Formation.exe"
Name: "{commondesktop}\Gestion De Stock"; Filename: "{app}\Projet_Fin_Formation.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Projet_Fin_Formation.exe"; Description: "{cm:LaunchProgram,Gestion De Stock}"; Flags: nowait postinstall skipifsilent

